import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { invoke } from '@tauri-apps/api/tauri'
import { listen } from '@tauri-apps/api/event'
import { useEffect, useState } from 'react'

// import Plot from 'react-plotly.js';
import dynamic from "next/dynamic";
const Plot = dynamic(() => import("react-plotly.js"), { ssr: false, })

const inter = Inter({ subsets: ['latin'] })

function clickLoadCsvButton() {
  invoke('load_csv', {}).then(console.log).catch(console.error)
}

// function MyPlot() {
//   return <Plot data={
//     [{
//       x: [1, 2, 3],
//       y: [4, 5, 6],
//       type: 'scatter',
//       mode: 'lines+markers',
//       marker: { color: 'red' },
//     },
//     { type: 'bar', x: [1, 2, 3], y: [4, 5, 6] }
//     ]
//   } layout={{ width: 320, height: 240, title: 'A Fancy Plot' }}
//   />;
// }

function MyPlot(data) {
  console.log(data);

  let data2 =
  [{
    x: [1, 2, 3],
    y: data.data,
    type: 'scatter',
    mode: 'lines+markers',
    marker: { color: 'red' },
  },
  { type: 'bar', x: [1, 2, 3], y: data.data }
  ];

  return <Plot data={ data2 }
  layout={{ width: 320, height: 240, title: 'A Fancy Plot' }}
  />;
}

export default function Home() {
  const [data, setData] = useState([7, 8, 9]);

  useEffect(() => {
    const _ = (async () => await listen<any>("event-name", (event) => {
      // console.log("abc");
      console.log(typeof(event.payload.data));
      console.log(typeof(event.payload.shape));
      const data = [Number(event.payload.data[0]), Number(event.payload.data[1]), Number(event.payload.data[2])];
      setData(data);
    }))();
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a className={styles.card}>
            <button onClick={clickLoadCsvButton}>Load CSV</button>
          </a>

          <a className={styles.card}>
            <MyPlot data={ data } />
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
